#coding=utf8
#!/usr/bin/env python
"""
Author:wuya @ smallteam
Date: 13-7-3
"""

from __future__ import division, print_function, unicode_literals

__metaclass__ = type

querys1 = [
    '数字化制造',
    '快速成型',
    '模型数据',
    '打印技术',
    'CAD技术',
    '3D打印',
    '复合材料',
    '模拟仿真',
    'CAD',
    '设计自动化',
    '参数化设计',
    '三维造型',
    '参数化建模',
    'CAE',
    'CAX',
    'RFID',
    '影响因素',
    '生态环境',
    '监测技术',
    '食品产业链',
    '物联网',
    '条码',
    '智能终端',
    '监管模式',
    '质量控制',
    '物联网',
    '中间件',
    'RFID',
    '传感器',
    '数据处理',
    '数据采集',
    '并行数据库',
    '大规模可扩展',
    'MapReduce',
    'Hadoop',
    '非结构化数据',
    '半结构化数据',
    '数据分析',
    '数据处理',
    '数据挖掘',
    '信息融合',
    '云计算',
    'digital manufacturing',
    'Rapid prototyping',
    'model data',
    'print technology',
    'CAD',
    '3D',
    'product design',
    'composite material',
    'printer',
    'analog simulation',
    'CAD',
    'design automation',
    'manufacturing',
    'parametric design',
    '3D-modeling',
    'parametric modeling',
    'expert system',
    'CAE',
    'CAX',
    'RFID',
    'food tracing',
    'influence factor',
    'ecology environment',
    'monitoring technology',
    'food industry chain',
    'internet of things',
    'bar code',
    'intelligent terminal',
    'supervision mode',
    'quality control',
    'internet of things',
    'middleware',
    'RFID',
    'sensor network',
    'intelligence',
    'construction',
    'platform. Video',
    'recognition',
    'data processing',
    'data collection',
    'parallel database',
    'large-scale extensible',
    'MapReduce',
    'Hadoop',
    'non-structured data',
    'semi-structured data',
    'data analysis',
    'data processing',
    'data mining',
    'information fusion',
    'cloud computing',
]

querys_zjcm = [
    "中国梦想秀",
    "非诚勿扰",
    "非你莫属",
    "舌尖上的中国",
    "中国好声音",
    "新闻联播",
    "周立波",
    "真人秀",
    "百里挑一",
    "快乐大本营",
    "温州",
    "中国星跳跃",
    "星跳水立方",
    "农夫山泉饮用天然水标准新闻发布会",
    "农夫山泉",
    "微信",
    "动物世界",
    "进击的巨人",
    "中国梦想秀 周立波",
    "中国最强音",
    "中国梦之声",
]